from app import db
from datetime import datetime
from app.models.client_scheme.student_model import Student
from app.models.client_scheme.student_details_models import (
    StudentFamily, StudentFamilyPhone, StudentFamilyEmail, 
    StudentAllergy, StudentMedicalPhone
)

def get_student_by_id(student_id):
    """
    Retrieve a student model instance by ID.
    """
    return Student.query.get(student_id)

def get_full_student_detail(student_id):
    """
    Get student by ID with full nested details (family, phones, emails).
    """
    student = Student.query.get(student_id)
    if not student:
        return None
    
    # Use to_dict with include_sensitive=True to get all base fields
    data = student.to_dict(include_sensitive=True)
    
    if student.familyId:
        family = StudentFamily.query.get(student.familyId)
        if family:
            family_data = family.to_dict()
            
            # Fetch phones and emails separately if they are not joined in the model
            phones = StudentFamilyPhone.query.filter_by(familyId=family.id).all()
            family_data['phones'] = [p.to_dict() for p in phones]
            
            emails = StudentFamilyEmail.query.filter_by(familyId=family.id).all()
            family_data['emails'] = [e.to_dict() for e in emails]
            
            data['family'] = family_data
            
    return data

def save_student_detail(student_id, data):
    """
    Save or Update student details.
    """
    if student_id:
        student = Student.query.get(student_id)
        if not student:
            return None, "Estudiante no encontrado"
    else:
        # For new students, generate a code if not provided
        student = Student()
        if not data.get('studentCode'):
            # Simple placeholder code logic if needed, 
            # though usually it might be generated by a sequence or service.
            student.studentCode = f"ST-{datetime.now().strftime('%y%m%s')}"
        db.session.add(student)

    # Helper function for int conversion
    def to_int(val):
        if val is None or val == '': return None
        try: return int(val)
        except: return val

    # 1. Base Information
    student.firstName = data.get('firstName')
    student.middleName = data.get('middleName')
    student.lastName = data.get('lastName')
    student.secondLastName = data.get('secondLastName')
    
    # Dates handling
    if data.get('birthDate'):
        try:
            # Handle ISO format or simple date
            bd_str = data['birthDate'].split('T')[0]
            student.birthDate = datetime.strptime(bd_str, '%Y-%m-%d').date()
        except: pass
        
    if data.get('enrollmentDate'):
        try:
            ed_str = data['enrollmentDate'].split('T')[0]
            student.enrollmentDate = datetime.strptime(ed_str, '%Y-%m-%d').date()
        except: pass

    student.genderId = to_int(data.get('genderId'))
    student.courseId = to_int(data.get('courseId'))
    student.livingSituation = to_int(data.get('livingSituation'))
    
    # Location
    student.countryId = to_int(data.get('countryId'))
    student.cityId = to_int(data.get('cityId'))
    student.sectorId = to_int(data.get('sectorId'))
    student.address = data.get('address')
    
    # Medical
    student.doctorName = data.get('doctorName')
    student.insuranceNumber = data.get('insuranceNumber')
    student.medicalInstitutionId = to_int(data.get('medicalInstitutionId'))
    student.insuranceInstitutionId = to_int(data.get('insuranceInstitutionId'))
    student.bloodTypeId = to_int(data.get('bloodTypeId'))
    
    # Academic/Others
    student.previousSchoolId = to_int(data.get('previousSchoolId'))
    student.entryReason = data.get('entryReason')
    student.exitReason = data.get('exitReason')

    # 2. Family Info
    student_family_id = data.get('studentFamilyId')
    family_data = data.get('family', {})
    
    if student_family_id:
        student.familyId = to_int(student_family_id)
        family = StudentFamily.query.get(student.familyId)
    elif family_data:
        if not student.familyId:
            family = StudentFamily()
            db.session.add(family)
            db.session.flush() 
            student.familyId = family.id
        else:
            family = StudentFamily.query.get(student.familyId)
    else:
        family = None

    if family:
        # Only update family basic fields if family_data is not empty
        if family_data:
            family.responsibleType = to_int(family_data.get('responsibleType'))
            family.paymentFrequencyId = to_int(family_data.get('paymentFrequencyId'))
            
            # Father
            father = family_data.get('father', {})
            if father:
                family.fatherFirstName1 = father.get('firstName1', family.fatherFirstName1)
                family.fatherFirstName2 = father.get('firstName2', family.fatherFirstName2)
                family.fatherLastName1 = father.get('lastName1', family.fatherLastName1)
                family.fatherLastName2 = father.get('lastName2', family.fatherLastName2)
                family.fatherDocument = father.get('document', family.fatherDocument)
                family.fatherDocumentTypeId = to_int(father.get('documentTypeId')) or family.fatherDocumentTypeId
                family.fatherProfessionId = to_int(father.get('professionId')) or family.fatherProfessionId
                family.fatherMaritalStatusId = to_int(father.get('maritalStatusId')) or family.fatherMaritalStatusId
            
            # Mother
            mother = family_data.get('mother', {})
            if mother:
                family.motherFirstName1 = mother.get('firstName1', family.motherFirstName1)
                family.motherFirstName2 = mother.get('firstName2', family.motherFirstName2)
                family.motherLastName1 = mother.get('lastName1', family.motherLastName1)
                family.motherLastName2 = mother.get('lastName2', family.motherLastName2)
                family.motherDocument = mother.get('document', family.motherDocument)
                family.motherDocumentTypeId = to_int(mother.get('documentTypeId')) or family.motherDocumentTypeId
                family.motherProfessionId = to_int(mother.get('professionId')) or family.motherProfessionId
                family.motherMaritalStatusId = to_int(mother.get('maritalStatusId')) or family.motherMaritalStatusId

            # Sync Phones (Only if not using existing family or if we want to overwrite)
            if not student_family_id:
                phones = family_data.get('phones', [])
                if phones:
                    StudentFamilyPhone.query.filter_by(familyId=family.id).delete()
                    for p in phones:
                        if p.get('phoneNumber'):
                            new_phone = StudentFamilyPhone(
                                familyId=family.id,
                                phoneTypeId=to_int(p.get('phoneTypeId')),
                                phoneNumber=p.get('phoneNumber'),
                                isPrincipal=p.get('isPrincipal', False)
                            )
                            db.session.add(new_phone)

                # Sync Emails
                emails = family_data.get('emails', [])
                if emails:
                    StudentFamilyEmail.query.filter_by(familyId=family.id).delete()
                    for e in emails:
                        if e.get('email'):
                            new_email = StudentFamilyEmail(
                                familyId=family.id,
                                email=e.get('email'),
                                isPrincipal=e.get('isPrincipal', False)
                            )
                            db.session.add(new_email)

    db.session.commit()
    return student.id, None